import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from "./providers";
import NavBar from '../components/NavBar';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className='min-h-[100vh]'>
            <NavBar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
